"use client";

import { useEffect, useState } from "react";
import { Activity, Boxes, Cloud, KeyRound, LayoutDashboard, MessageSquare, Network, Plus, ServerCog, Settings2, ShieldCheck, Sparkles } from "lucide-react";
import { motion } from "framer-motion";
import { useQuery } from "@tanstack/react-query";
import { API_BASE, api, type Model, type Server, type Summary } from "../lib/api";
import { usePanelStore } from "../lib/store";

const nav = [
  ["overview", "Overview", LayoutDashboard], ["chat", "Chat playground", MessageSquare], ["models", "Models", Boxes], ["servers", "Servers", ServerCog], ["providers", "Providers", Cloud], ["deployments", "Deployments", Network], ["keys", "API keys", KeyRound],
] as const;

function Status({ value }: { value: string }) { return <span className={`status ${value}`}>{value}</span>; }

function useData(enabled: boolean) {
  return {
    summary: useQuery({ queryKey: ["summary"], queryFn: () => api<Summary>("/api/dashboard/summary"), enabled }),
    servers: useQuery({ queryKey: ["servers"], queryFn: () => api<Server[]>("/api/servers"), enabled }),
    models: useQuery({ queryKey: ["models"], queryFn: () => api<Model[]>("/api/models"), enabled }),
  };
}

function AuthScreen({ bootstrap, onSuccess }: { bootstrap: boolean; onSuccess: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [displayName, setDisplayName] = useState("Administrator"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError(""); setBusy(true);
    try { const path = bootstrap ? "/api/auth/bootstrap" : "/api/auth/login"; const body = bootstrap ? { email, password, display_name: displayName } : { email, password }; const response = await fetch(`${API_BASE}${path}`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.detail ?? `HTTP ${response.status}`); onSuccess(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Authentication failed"); } finally { setBusy(false); }
  }
  return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 20 }}><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="card" style={{ width: "min(430px, 100%)", padding: 28 }}><div className="brand" style={{ padding: 0, marginBottom: 30 }}><div className="brand-mark" /><div><strong>LlamaGrid</strong><small>secure control plane</small></div></div><div className="eyebrow">{bootstrap ? "First-run setup" : "Operator access"}</div><h1 style={{ fontSize: 28, marginBottom: 8 }}>{bootstrap ? "Create the administrator" : "Welcome back"}</h1><p className="muted" style={{ lineHeight: 1.55 }}>{bootstrap ? "Bootstrap the first local account. The backend stores only an Argon2 password hash." : "Sign in to manage models, servers and deployments."}</p><form onSubmit={submit} style={{ display: "grid", gap: 11, marginTop: 22 }}>{bootstrap && <input className="input" value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="Display name" required />}<input className="input" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" required /><input className="input" type="password" minLength={bootstrap ? 14 : 1} value={password} onChange={(e) => setPassword(e.target.value)} placeholder={bootstrap ? "Password (14+ characters)" : "Password"} required />{error && <div style={{ color: "var(--red)", fontSize: 12 }}>{error}</div>}<button className="btn primary" disabled={busy}>{busy ? "Working…" : bootstrap ? "Initialize control plane" : "Sign in"}</button></form></motion.div></main>;
}

function Overview({ data }: { data: ReturnType<typeof useData> }) {
  const summary = data.summary.data; const servers = data.servers.data ?? [];
  const metrics = [["Healthy nodes", `${summary?.healthy_servers ?? "—"}/${summary?.servers ?? "—"}`, "live cluster"], ["Registered models", summary?.models ?? "—", "catalog + deployments"], ["Active deployments", summary?.deployments ?? "—", "rolling strategy"], ["Control jobs", summary?.running_jobs ?? "—", "queued / running"]];
  return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><div className="grid grid-4">{metrics.map(([label, value, foot]) => <div className="card metric" key={label}><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-foot">● {foot}</div></div>)}</div><div className="grid grid-2 section"><div className="card"><div className="section-head"><div><div className="eyebrow">Inference fabric</div><h2>Existing production cluster</h2></div><Status value="deployed" /></div><p className="muted">The panel observes and operates the current replica fleet without changing dispatcher or worker tuning.</p><div className="bar"><span style={{ width: `${summary?.servers ? Math.round(((summary.healthy_servers || 0) / summary.servers) * 100) : 0}%` }} /></div><p className="muted" style={{ fontSize: 12, marginBottom: 0 }}>{summary?.inference.model} · {summary?.inference.replicas ?? 0} replicas · {summary?.inference.context_length?.toLocaleString?.() ?? "automatic"} context</p></div><div className="card"><div className="section-head"><div><div className="eyebrow">Capacity map</div><h2>Node health</h2></div><Activity size={16} style={{ color: "var(--green)" }} /></div>{servers.slice(0, 8).map((server) => <div key={server.id} style={{ display: "flex", justifyContent: "space-between", padding: "8px 0", borderBottom: "1px solid rgba(136,157,190,.1)" }}><span>{server.name} <span className="muted mono">{server.private_ip}</span></span><Status value={server.status} /></div>)}{servers.length > 8 && <p className="muted" style={{ fontSize: 12 }}>+ {servers.length - 8} more nodes</p>}</div></div></motion.div>;
}

function Chat({ models }: { models: Model[] }) {
  const [prompt, setPrompt] = useState(""); const [messages, setMessages] = useState<{ role: string; content: string }[]>([]); const [busy, setBusy] = useState(false);
  const [model, setModel] = useState(models[0]?.model_id ?? "");
  useEffect(() => { if (!model && models[0]?.model_id) setModel(models[0].model_id); }, [model, models]);
  async function send() {
    if (!model || !prompt.trim() || busy) return; const userPrompt = prompt.trim(); setPrompt(""); setMessages((m) => [...m, { role: "user", content: userPrompt }, { role: "assistant", content: "" }]); setBusy(true);
    try { const response = await fetch(`${API_BASE}/api/chat/completions`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ model, messages: [{ role: "user", content: userPrompt }], stream: true, max_tokens: 512 }) }); if (!response.ok || !response.body) throw new Error(`Request failed: ${response.status}`); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split("\n"); buffer = lines.pop() ?? ""; for (const line of lines) { if (!line.startsWith("data:")) continue; const value = line.slice(5).trim(); if (value === "[DONE]") continue; try { const delta = JSON.parse(value)?.choices?.[0]?.delta?.content ?? ""; if (delta) setMessages((m) => m.map((msg, i) => i === m.length - 1 ? { ...msg, content: msg.content + delta } : msg)); } catch { /* partial SSE frame */ } } } } catch (cause) { setMessages((m) => m.map((msg, i) => i === m.length - 1 ? { ...msg, content: `Error: ${cause instanceof Error ? cause.message : "request failed"}` } : msg)); } finally { setBusy(false); }
  }
  return <div className="card chat"><div style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 12 }}><span className="eyebrow">Model</span><select className="input" value={model} onChange={(event) => setModel(event.target.value)} disabled={busy}>{models.length === 0 && <option value="">No deployed model</option>}{models.map((item) => <option key={item.id} value={item.model_id}>{item.display_name} · {item.model_id}</option>)}</select></div><div className="messages">{messages.length === 0 && <div className="empty"><Sparkles size={28} style={{ color: "var(--cyan)", marginBottom: 10 }} /><br />Ask the selected model something. Tokens will appear live over SSE.</div>}{messages.map((m, i) => <div className={`message ${m.role}`} key={i}><span className="eyebrow">{m.role}</span><br />{m.content || (busy && m.role === "assistant" ? "▌" : "")}</div>)}</div><div className="composer"><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void send(); } }} placeholder="Message the selected model…" /><button className="btn primary" onClick={() => void send()} disabled={busy || !model}>{busy ? "Generating…" : "Send"}</button></div></div>;
}

function Models({ models }: { models: Model[] }) { const [q, setQ] = useState(""); const [results, setResults] = useState<any[]>([]); async function search() { if (q.length >= 2) setResults(await api<any[]>(`/api/models/search?q=${encodeURIComponent(q)}`)); } return <div className="grid grid-2"><div className="card"><div className="section-head"><div><div className="eyebrow">Catalog</div><h2>Installed & available models</h2></div><button className="btn"><Plus size={15} /> Add</button></div>{models.map((m) => <div key={m.id} style={{ padding: "14px 0", borderBottom: "1px solid rgba(136,157,190,.1)" }}><div style={{ display: "flex", justifyContent: "space-between" }}><strong>{m.display_name}</strong><Status value={m.status} /></div><div className="muted mono" style={{ marginTop: 5 }}>{m.model_id}</div><div className="muted" style={{ fontSize: 12, marginTop: 7 }}>{m.quantization ?? "custom"} · context {m.context_length?.toLocaleString() ?? "auto"}</div></div>)}</div><div className="card"><div className="eyebrow">Model registry</div><h2>Discover a model</h2><p className="muted">Search first; install is then represented as a tracked, resumable deployment job.</p><div style={{ display: "flex", gap: 8 }}><input className="input" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search by model or repository" /><button className="btn primary" onClick={() => void search()}>Search</button></div>{results.slice(0, 8).map((item) => <div key={item.id} style={{ padding: "11px 0", borderBottom: "1px solid rgba(136,157,190,.1)" }}><strong>{item.id}</strong><div className="muted" style={{ fontSize: 12 }}>{item.pipeline_tag ?? "model"} · downloads {item.downloads?.toLocaleString?.() ?? "—"}</div></div>)}</div></div>; }

function Servers({ servers }: { servers: Server[] }) { return <div className="card"><div className="section-head"><div><div className="eyebrow">Infrastructure</div><h2>Server inventory</h2></div><button className="btn primary"><Plus size={15} /> Add server</button></div><table className="table"><thead><tr><th>Name</th><th>Private address</th><th>Provider</th><th>Status</th><th>Port</th></tr></thead><tbody>{servers.map((s) => <tr key={s.id}><td><strong>{s.name}</strong></td><td className="mono">{s.private_ip}</td><td>{s.provider}</td><td><Status value={s.status} /></td><td>{s.rpc_port}</td></tr>)}</tbody></table></div>; }

function Deployments() { return <div className="grid grid-2"><div className="card"><div className="eyebrow">Orchestration</div><h2>Model deployments</h2><p className="muted">Create a model placement plan, select up to 500 eligible servers, then follow canary and rolling progress in real time.</p><div style={{ display: "grid", gap: 10, marginTop: 18 }}><input className="input" placeholder="Deployment name" /><select><option>Choose a registered model</option></select><select><option>Rolling update</option><option>Canary first</option></select><button className="btn primary">Create deployment plan</button></div></div><div className="card"><div className="section-head"><div><div className="eyebrow">Lifecycle</div><h2>Safe state machine</h2></div><ShieldCheck size={18} style={{ color: "var(--green)" }} /></div>{["Validate", "Provision", "Download + verify", "Canary", "Roll out", "Healthy"].map((item, i) => <div key={item} style={{ display: "flex", gap: 12, alignItems: "center", padding: "10px 0" }}><div className="avatar" style={{ width: 24, height: 24, background: i < 3 ? "var(--cyan)" : "rgba(136,157,190,.2)", color: "#071017" }}>{i + 1}</div><span>{item}</span><span className="muted" style={{ marginLeft: "auto", fontSize: 12 }}>{i < 3 ? "ready" : "queued"}</span></div>)}</div></div>; }

function Keys() { return <div className="card"><div className="section-head"><div><div className="eyebrow">Access control</div><h2>API keys</h2></div><button className="btn primary"><Plus size={15} /> Generate key</button></div><div className="empty"><KeyRound size={24} style={{ color: "var(--cyan)" }} /><br />Keys are hashed at rest and shown only once after creation.</div></div>; }

function FunctionalModels({ models }: { models: Model[] }) { const [query, setQuery] = useState(""); const [results, setResults] = useState<any[]>([]); async function search() { if (query.length >= 2) setResults(await api<any[]>(`/api/models/search?q=${encodeURIComponent(query)}`)); } async function add(modelId: string) { await api("/api/models", { method: "POST", body: JSON.stringify({ model_id: modelId, display_name: modelId.split("/").pop(), source_ref: modelId }) }); window.location.reload(); } return <div className="grid grid-2"><div className="card"><div className="section-head"><div><div className="eyebrow">Catalog</div><h2>Installed & available models</h2></div><button className="btn" onClick={() => { const id = window.prompt("Hugging Face model ID"); if (id) void add(id); }}><Plus size={15} /> Add</button></div>{models.map((m) => <div key={m.id} style={{ padding: "14px 0", borderBottom: "1px solid rgba(136,157,190,.1)" }}><div style={{ display: "flex", justifyContent: "space-between" }}><strong>{m.display_name}</strong><Status value={m.status} /></div><div className="muted mono" style={{ marginTop: 5 }}>{m.model_id}</div><div className="muted" style={{ fontSize: 12, marginTop: 7 }}>{m.quantization ?? "custom"} · context {m.context_length?.toLocaleString() ?? "auto"}</div></div>)}</div><div className="card"><div className="eyebrow">Hugging Face</div><h2>Discover a model</h2><p className="muted">Search the public catalog, then add a model to the control-plane registry.</p><div style={{ display: "flex", gap: 8 }}><input className="input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="e.g. Qwen coder" /><button className="btn primary" onClick={() => void search()}>Search</button></div>{results.slice(0, 8).map((item) => <div key={item.id} style={{ display: "flex", alignItems: "center", gap: 10, padding: "11px 0", borderBottom: "1px solid rgba(136,157,190,.1)" }}><div style={{ flex: 1 }}><strong>{item.id}</strong><div className="muted" style={{ fontSize: 12 }}>{item.pipeline_tag ?? "model"} · downloads {item.downloads?.toLocaleString?.() ?? "—"}</div></div><button className="btn" onClick={() => void add(item.id)}>Register</button></div>)}</div></div>; }

function FunctionalServers({ servers }: { servers: Server[] }) { async function add() { const name = window.prompt("Server name"); const private_ip = window.prompt("Private address or hostname"); const port = Number(window.prompt("Model API port", "8080")); if (name && private_ip && Number.isInteger(port) && port > 0 && port <= 65535) { await api("/api/servers", { method: "POST", body: JSON.stringify({ name, private_ip, provider: "existing", rpc_port: port }) }); window.location.reload(); } } return <div className="card"><div className="section-head"><div><div className="eyebrow">Infrastructure</div><h2>Server inventory</h2></div><button className="btn primary" onClick={() => void add()}><Plus size={15} /> Add server</button></div><table className="table"><thead><tr><th>Name</th><th>Private address</th><th>Provider</th><th>Status</th><th>Port</th></tr></thead><tbody>{servers.map((s) => <tr key={s.id}><td><strong>{s.name}</strong></td><td className="mono">{s.private_ip}</td><td>{s.provider}</td><td><Status value={s.status} /></td><td>{s.rpc_port}</td></tr>)}</tbody></table></div>; }

function FunctionalDeployments({ models }: { models: Model[] }) { const [modelId, setModelId] = useState(models[0]?.id ?? ""); const [replicas, setReplicas] = useState(1); const [job, setJob] = useState<{ progress: number; message: string; status: string } | null>(null); async function create() { const deployment = await api<{ job_id: string }>("/api/deployments", { method: "POST", body: JSON.stringify({ name: `deployment-${Date.now()}`, model_id: modelId, desired_replicas: replicas, strategy: "rolling" }) }); setJob({ progress: 0, message: "Queued", status: "queued" }); const stream = new EventSource(`${API_BASE}/api/jobs/${deployment.job_id}/events`); stream.addEventListener("progress", (event) => setJob(JSON.parse((event as MessageEvent).data))); stream.addEventListener("done", (event) => { setJob(JSON.parse((event as MessageEvent).data)); stream.close(); }); } return <div className="grid grid-2"><div className="card"><div className="eyebrow">Orchestration</div><h2>Model deployments</h2><p className="muted">Create an idempotent plan and follow its canary/rolling lifecycle. Current inference replicas are not restarted by this generic plan.</p><div style={{ display: "grid", gap: 10, marginTop: 18 }}><input className="input" value={models.find((m) => m.id === modelId)?.display_name ?? ""} readOnly placeholder="Register a model first" /><input className="input" type="number" min={1} max={500} value={replicas} onChange={(e) => setReplicas(Number(e.target.value))} /><button className="btn primary" disabled={!modelId || !!job} onClick={() => void create()}>Create deployment plan</button></div></div><div className="card"><div className="section-head"><div><div className="eyebrow">Live job</div><h2>{job ? job.status : "Ready"}</h2></div><ShieldCheck size={18} style={{ color: "var(--green)" }} /></div>{job ? <><p className="muted">{job.message}</p><div className="bar"><span style={{ width: `${job.progress}%` }} /></div><p className="muted" style={{ fontSize: 12 }}>{job.progress}% · events are streamed from the backend</p></> : <div className="empty">Create a plan to see state transitions here.</div>}</div></div>; }

function FunctionalKeys() { const [key, setKey] = useState(""); async function create() { const result = await api<{ key: string }>("/api/api-keys", { method: "POST", body: JSON.stringify({ name: "Panel-generated key" }) }); setKey(result.key); } return <div className="card"><div className="section-head"><div><div className="eyebrow">Access control</div><h2>API keys</h2></div><button className="btn primary" onClick={() => void create()}><Plus size={15} /> Generate key</button></div>{key ? <div style={{ marginTop: 20 }}><div className="muted" style={{ fontSize: 12 }}>Copy this secret now; it will not be shown again.</div><div className="input mono" style={{ marginTop: 8, overflow: "auto" }}>{key}</div></div> : <div className="empty"><KeyRound size={24} style={{ color: "var(--cyan)" }} /><br />Keys are hashed at rest and shown only once after creation.</div>}</div>; }

function FunctionalProviders() { const [name, setName] = useState("Hetzner Cloud"); const [token, setToken] = useState(""); const [credentials, setCredentials] = useState<{ id: string; name: string; provider: string; is_active: boolean }[]>([]); useEffect(() => { void api<typeof credentials>("/api/providers/credentials").then(setCredentials); }, []); async function save() { await api("/api/providers/credentials", { method: "POST", body: JSON.stringify({ name, provider: "hetzner", token }) }); setToken(""); const next = await api<typeof credentials>("/api/providers/credentials"); setCredentials(next); } return <div className="grid grid-2"><div className="card"><div className="eyebrow">Cloud providers</div><h2>Add a Hetzner credential</h2><p className="muted">The token is encrypted before PostgreSQL persistence and never returned by the API.</p><div style={{ display: "grid", gap: 10, marginTop: 18 }}><input className="input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Credential name" /><input className="input" type="password" value={token} onChange={(e) => setToken(e.target.value)} placeholder="Hetzner API token" /><button className="btn primary" disabled={token.length < 20} onClick={() => void save()}>Save encrypted credential</button></div></div><div className="card"><div className="section-head"><div><div className="eyebrow">Connected accounts</div><h2>Provider inventory</h2></div><Cloud size={18} style={{ color: "var(--cyan)" }} /></div>{credentials.length ? credentials.map((item) => <div key={item.id} style={{ display: "flex", justifyContent: "space-between", padding: "12px 0", borderBottom: "1px solid rgba(136,157,190,.1)" }}><span><strong>{item.name}</strong><br /><span className="muted" style={{ fontSize: 12 }}>{item.provider}</span></span><Status value={item.is_active ? "healthy" : "failed"} /></div>) : <div className="empty">No provider credential is connected.</div>}</div></div>; }

function renderView(view: string, data: ReturnType<typeof useData>) { if (view === "chat") return <Chat models={data.models.data ?? []} />; if (view === "models") return <FunctionalModels models={data.models.data ?? []} />; if (view === "servers") return <FunctionalServers servers={data.servers.data ?? []} />; if (view === "providers") return <FunctionalProviders />; if (view === "deployments") return <FunctionalDeployments models={data.models.data ?? []} />; if (view === "keys") return <FunctionalKeys />; return <Overview data={data} />; }

export default function Home() {
  const { view, setView } = usePanelStore(); const [auth, setAuth] = useState<"loading" | "login" | "bootstrap" | "ready">("loading"); const data = useData(auth === "ready"); const [ready, setReady] = useState(false);
  useEffect(() => { setReady(true); void fetch(`${API_BASE}/api/auth/status`, { credentials: "include" }).then((response) => response.json()).then(async (status: { bootstrap_required: boolean }) => { if (status.bootstrap_required) { setAuth("bootstrap"); return; } const me = await fetch(`${API_BASE}/api/auth/me`, { credentials: "include" }); setAuth(me.ok ? "ready" : "login"); }).catch(() => setAuth("login")); }, []);
  if (auth === "loading") return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center" }}><div className="muted">Loading secure control plane…</div></main>;
  if (auth !== "ready") return <AuthScreen bootstrap={auth === "bootstrap"} onSuccess={() => setAuth("ready")} />;
  const title = nav.find(([id]) => id === view)?.[1] ?? "Overview";
  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark" /><div><strong>LlamaGrid</strong><small>control plane</small></div></div><nav className="nav">{nav.map(([id, label, Icon]) => <button className={view === id ? "active" : ""} key={id} onClick={() => setView(id)}><Icon size={17} /><span>{label}</span></button>)}</nav><div className="sidebar-note"><Activity size={16} style={{ color: "var(--green)" }} /><br />All inference traffic stays on the private worker fabric. This panel is the operational layer.</div></aside><main className="main"><div className="topbar"><div><div className="eyebrow">{ready ? "Live control surface" : "Loading"}</div><h1>{title}</h1></div><div className="user-pill"><div className="avatar">B</div> Administrator <Settings2 size={14} /></div></div><div key={view}>{renderView(view, data)}</div></main></div>;
}
